---
title: my experience in summer 2020 research
layout: page
---
remote_theme: pmarsceill/just-the-docs
one thing I will take away from this experience
one thing I am thinking about doing
https://mybinder.org/v2/gh/annecss/summer2020notebooks/master
---
